export enum DebitCategoryEnum {
  HOUSING = 'HOUSING',
  TRANSPORTATION = 'TRANSPORTATION',
  FOOD = 'FOOD',
  UTILITIES = 'UTILITIES',
  INSURANCE = 'INSURANCE',
  MEDICAL = 'MEDICAL',
  PERSONAL_SPENDING = 'PERSONAL_SPENDING',
  ENTERTAINMENT = 'ENTERTAINMENT',
  MISCELLANEOUS = 'MISCELLANEOUS',
  TAXES = 'TAXES',
}
